server:
  port: 8081

spring:
  application:
    name: user-service

  # 👇 👇 👇 我给你加上了 Nacos 注册配置！！！ 👇 👇 👇
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

  datasource:
    url: jdbc:mysql://localhost:3306/fresh_shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: Ls010203
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    database: 0

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true