server:
  port: 8085

spring:
  application:
    name: file-service

  # ✅ 加上 Nacos 注册（必须加！）
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

  redis:
    host: localhost
    port: 6379
    database: 3

  web:
    resources:
      static-locations: file:D:/upload/

# 图片访问映射
mvc:
  static-path-pattern: /file/**