server:
  port: 8082

spring:
  application:
    name: order-service

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

  datasource:
    url: jdbc:mysql://localhost:3306/fresh_shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: Ls010203
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    database: 0

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: order-service-group

# Seata 单机客户端配置
seata:
  tx-service-group: freshshop_tx_group
  config:
    type: file
  registry:
    type: file
  service:
    vgroup-mapping:
      freshshop_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
  # 开启数据源代理（AT模式必需）
  datasource:
    proxy:
      enable: true