server:
  port: 8084

spring:
  application:
    name: marketing-service

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

  datasource:
    url: jdbc:mysql://localhost:3306/fresh_shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Ls010203
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    database: 0

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: marketing-group

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

# 统一 Seata 配置
seata:
  tx-service-group: freshshop_tx_group
  config:
    type: file
  registry:
    type: file
  service:
    vgroup-mapping:
      freshshop_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
  datasource:
    proxy:
      enable: true
  transport:
    serialization: seata
    compressor: none
    max-frame-size: 20971520