<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <!-- 继承你的正确父工程 -->
    <parent>
        <groupId>org.example</groupId>
        <artifactId>cloud-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>fresh-shop-gateway</artifactId>

    <dependencies>
        <!-- 网关核心依赖（强制写版本，确保一定能下载） -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
            <version>4.0.6</version>
        </dependency>

        <!-- 公共包 -->
        <dependency>
            <groupId>org.example</groupId>
            <artifactId>common-api</artifactId>
        </dependency>

    </dependencies>

</project>